[package]
name = "darwin"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
pixels = "0.13"
image = "0.25"
cpal = "0.15"
log = "0.4.29"
env_logger = "0.11.8"
anyhow = "1.0.100"
